### ISSUE TITLE
issueベースの開発レビュー依頼

### ISSUE THREAD

**Issue by asano-masayuki** [asano-masayuki/MVP_runteq#49]
### 実装予定機能
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] パスワード変更機能
- [ ] メールアドレス変更機能
- [ ] プロフィール画像変更機能
- [ ] 分析機能の個別設定（重要度割合）機能
- [ ] ユーザーフォロー機能
- [ ] ユーザーフォロー解除
- [ ] DM機能
- [ ] 経済指標の相関分析、予測
- [ ] 過去データcsvファイルで出力機能
- [ ] 重要度設定によるカスタマイズ分析
- [ ] 経済指標データの取得、グラフ化
- [ ] ユーザー成績/履歴表示
- [ ] アラート設定
- [ ] いいね機能
- [ ] いいね解除機能
- [ ] トレンド予想のアンケート投票機能
- [ ] 週or月で新しい掲示板自動作成機能
- [ ] ユーザー成績ランキング

## 必要なページ
- [ ] トップページ
- [ ] ログインページ
- [ ] 新規登録ページ
- [ ] パスワード再発行手続きページ
- [ ] 新パスワード設定ページ
- [ ] 新アドレス設定ページ
- [ ] MYページ
- [ ] ユーザーフォロー一覧ページ
- [ ] ユーザー詳細
- [ ] DM通知
- [ ] ユーザー個別設定ページ
- [ ] ランキングページ
- [ ] 為替予想ページ
- [ ] 経済指標一覧ページ
- [ ] 経済指標分析ページ
- [ ] 掲示板

**Comment by asano-masayuki** [comment]
よろしくお願いいたします。
2024/7/19リリースできるように努力しますが、おそらく延長プランを申し込むと思います。

**Comment by tmtkzk0823** [comment]
確認しました。
概ね良さそうです！
LGTMです！
